AWSTemplateFormatVersion: '2010-09-09'
Resources:
  MyS3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: 'joy-s3tbl-bucket'
      AccessControl: Private
      MetadataTableConfiguration:
        S3TablesDestination:
          BucketName: 'joy-s3tbl-bucket'
          TableName: 'joy-s3metadata-tbl'
